### ISSUE TITLE
Sprint 1: Navbar

### ISSUE THREAD

**Issue by sgilfeather** [JumboCode/TheLegacyProject#4]
Your first task: to create a simple Navbar! Our official design isn't out yet, so the font and color palette you choose is flexible. However, your Navbar should model some of the examples shown below: base your Navbar off the bottom example. Put your `<Navbar />` in the file `utils.tsx` within `src`.

🎯 : Chris Burke, Loc Mai, Alexander Lee

**TODO:**
- [x] A component, called `<Navbar />`, which contains several clickable elements. This should be reusable for both the landing page and member view page.
- [x] A logo component with text "The Legacy Project", which floats within the Navbar to the right.
- [x] Two clickable components, "About" and "Contact Us", which float within the Navbar to the left.
- [x] A clickable button, "Log in with Google", which floats within the Navbar to the right.

Think about how you can create (and pass...) reusable components to put items in the Navbar (we love modularity). And, consider the dimensions of the website: what happens when a user reduces their screen width? 

If you finish that, then
- [x] Set up media queries: when a page's width is reduced enough, the Navbar can collapse into a "mobile view"– all components disappear, and are replaced with a dropdown menu icon. Clicking on this icon opens a dropdown with each component. 
- [x] Set up routing for the "Log in with Google" button. This will eventually lead to a 'Log in with Google' page, but for now, link it to `google.com`.

Tailwind tutorial on **media queries**: [https://tailwindcss.com/docs/screens](url)
Next.js tutorial on **routing**: [https://nextjs.org/docs/routing/introduction](url)

![image](https://user-images.githubusercontent.com/42349909/197619341-a4dc7dfc-92ef-4542-ab2f-9f6f147b7158.png)
