### ISSUE TITLE
Sprint 1: Note Grid

### ISSUE THREAD

**Issue by sgilfeather** [JumboCode/TheLegacyProject#5]
Your first task: to create a simple grid view for notes! Our official design isn't out yet, so the font and color palette you choose is flexible. This is scaffolding for the final Senior Entry page, which stores note entries for each senior interviewee. Very similar to Google Drive (reference included below). Write your components in a file titled `senior-profile.tsx` within `src/pages`. 

🎯 : Jo Chung, Joe Carpenter, Taarika Bala

**TODO:**
- [x] A main component, called `<FileGrid />`, which contains a flex box arrangement of `<FileBox/>` components.
- [x] Each `<File />` component should take props:`name` (string), `URL` (string), `type` (string), and `last_modified` (a Typescript `Date` object).
- [x] #7
- [x] On click, the specified `URL` should be opened in a new tab.

If you finish that, then you can...
- [x] Set up some nice visuals! Add a a drop shadow, or a subtle animation on hover.
- [x] Instead of using a string, define an enum for several potential file types (document, pdf, or audio clipping). Upon passing a certain enum to a `<FileBox />`, a given icon is shown in the box for that file type.

<img width="869" alt="Screen Shot 2022-10-24 at 20 20 31" src="https://user-images.githubusercontent.com/42349909/197654489-fd3870e3-22aa-4cdf-aca4-425fd2ec3a40.png">
