### ISSUE TITLE
Sprint 1: Google Drive API

### ISSUE THREAD

**Issue by sgilfeather** [JumboCode/TheLegacyProject#6]
Your first task: to look into the Google Drive API! While we plan our integration of the Google Drive API into the project, we'd love for you to get familiar with the API itself. This is great preparatory work for an API that we'll be using heavily throughout the project. You will be writing a component, `<OAuthDemo />`, to recreate the OAuth 2.0 Google Drive demo. Write your in a code titled `drive-demo.tsx` within `src`. 

Complete the walkthrough here [https://developers.google.com/drive/api/quickstart/js](https://developers.google.com/drive/api/quickstart/js). However, instead of creating an `index.html` file, create a React Typescript file with the component `<OAuthDemo />`. This component will define the given functions `handleAuthClick()`, `handleSignoutClick()`, etc. as defined in the walkthrough. And, the component will return (render) the given HTML elements, which take these functions as their `onClick` handlers. 

🎯 : Siara Small, Alyssa Williams, Jojo Zhang, Amitav Nott

**TODO:**
- [x] Read through the given walkthrough. Follow its instructions to setup an OAuth 2.0 Client ID and set up the demo application, which authorizes a user through Google Drive and logs them out.
- [ ] Create `drive-demo.tsx`, and draft out the component `<OAuthDemo />`, given the starter code provided in the walkthrough. Translate their vanilla Javascript and HTML into Typescript and React.

If you finish that, then you can...
- [ ] Explore the Google Drive API documentation! Look at how the API handles file uploads, modifications, and other Google Drive functionalities.
